### ISSUE TITLE
lerna-alias and react-dev-utils/ModuleScopePlugin

### ISSUE THREAD

**Issue by dforsl** [Andarist/lerna-alias#1]
Hi!

First, let me say that it's great stuff - just what I've been looking for!

We have a monorepo, using lerna, of react libs and apps. We use webpack for building, and use ModuleScopePlugin from react-dev-utils to control how imports are made. More on the plugin here: https://www.npmjs.com/package/react-dev-utils. But issues then appear when we use lerna-alias, as aliases appear to reference the "fulll" paths of dependencies that are present in the monorepo. Would it be possible to, through eg. a flag, reference used dependencies through the lib's own node_modules, where symlinks should be present?

Any thoughts on this?
/d

**Comment by Andarist** [comment]
First community issue 🎉.

I use this in combination with `react-dev-utils` too (in projects bootstrapped with CRA) and I just do this in my webpack config:
```js
// ...
plugins: [
  new ModuleScopePlugin(paths.appSrc, [
    paths.appPackageJson,
    ...Object.values(lernaAliases())
  ])
],
```

Does this answer your question? If not I'm sure we'll be able to figure out some other solution for you :)

**Comment by Andarist** [comment]
Closing the issue because it got quite stale, if you have any further questions or problems please open a new issue.

**Comment by dforsl** [comment]
Hi!

Sorry, it got consumed by a bunch of other things at the same time. 

Your solution worked great! I'd prefer to be able to truly enforce the module scope to ensure that no unfortunate coupling sneaks its way in. I'll ping if I ever get the time to look into it :-)

Thanks again!
