### ISSUE TITLE
Click to definition in vscode

### ISSUE THREAD

**Issue by penx** [Andarist/lerna-alias#11]
Any ideas how to get click to definition in vscode to link to src folder for named imports in a js monorepo?

**Comment by Andarist** [comment]
I think this can be done either with `tsconfig.json`'s [`paths`](https://www.typescriptlang.org/tsconfig#paths) or with [project references](https://www.typescriptlang.org/docs/handbook/project-references.html).

Nowadays I've switched to using [`preconstruct`](https://github.com/preconstruct/preconstruct) for my monorepos and things "just work" after running `preconstruct dev` in the monorepo's `postinstall` script.
